title: 'Watercolors by Muriel Libert'
author:
  name: 'Muriel Libert'
  email: sprout6t@gmail.com
taxonomies:
  - category
  - tag
metadata:
  description: 'An exclusive HTML5/CSS3 freebie by Peter Finlan, for Codrops.'
summary:
  enabled: false
  format: short
  size: 300
  delimiter: '==='
blog:
  route: /blog
header:
  logo: ./user/themes/ceevee/images/logo.png
  description: '<span>Muriel Libert</span> is a watercolor artist from <span>Belgium</span> who has been living in the <span>United States</span> for <span>30 years.</span>'
